### ISSUE TITLE
Can You provide any example how to use this API?

### ISSUE THREAD

**Issue by yaswanthgosula** [d7laungani/DLLocalNotifications#1]
When I tried to use with pods it's giving me error saying DLnotificationscheduler initializer is inaccessible due to internal protection

**Comment by yaswanthgosula** [comment]
it would help me lot in my current app in which i am going to trigger notification on geo-fenced area.

**Comment by d7laungani** [comment]
Hello,

There was some errors that I fixed and it should work now. Re-install the pod and make sure it updates to release 0.04. The documentation for the location function can be found [here](https://github.com/d7laungani/DLLocalNotifications#location-based-notification)
