### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by conegit** [d7laungani/DLLocalNotifications#11]
Is it possible to detect push-notification arrival?

**Comment by d7laungani** [comment]
They way this library is designed it is not possible .

**Comment by d7laungani** [comment]
Sorry for my hasty reply but if you are referring to being able to detect when one of the notficiations you send is called you can use this block of code. It is not a function of my library but a part of Apple's protocol.

` func application(_ application: UIApplication, didReceive notification: UILocalNotification) {
        
        if ( application.applicationState == UIApplicationState.active) {
            print("Active")
            // App is foreground and notification is recieved,
            // Show a alert.
            if #available(iOS 8.2, *) {
                UIAlertView(title: notification.alertTitle, message: notification.alertBody, delegate: nil, cancelButtonTitle: "OK").show()
            } else {
                print("Received Local Notification:")
                print(notification.alertBody)
            }
            
        } else if( application.applicationState == UIApplicationState.background) {
            print("Background")
            // App is in background and notification is received,
            // You can fetch required data here don't do anything with UI.
        } else if( application.applicationState == UIApplicationState.inactive) {
            print("Inactive")
            // App came in foreground by used clicking on notification,
            // Use userinfo for redirecting to specific view controller.
            
        }
    }`
