### ISSUE TITLE
Cannot delete notification with identifier

### ISSUE THREAD

**Issue by megataps** [d7laungani/DLLocalNotifications#14]

**Comment by d7laungani** [comment]
You can now delete a notification  scheduler.cancelNotification(notification: notification). If you don't have the original notification just create a dummy notification with your identifier. 
E.g. 

`let firstNotification = DLNotification(identifier: <YOUR IDENTIFIER>, alertTitle: "", alertBody: "", date: Date(), repeats: .minute)`
