### ISSUE TITLE
podfile install issue

### ISSUE THREAD

**Issue by raguiar2** [d7laungani/DLLocalNotifications#21]
I have an issue installing this from the master branch. 

When i run 'pod install' on the app with the line
`  pod 'DLLocalNotifications', '~>0.06'` 
in my podfile, I get the following line of code

`            content.sound = (notification.soundName == nil) ? UNNotificationSound.default() : UNNotificationSound.init(named: notification.soundName!)`

However, I noticed that this is replaced by 

`            content.sound = notification.soundName == "" ? UNNotificationSound.default : UNNotificationSound.init(named: UNNotificationSoundName(rawValue: notification.soundName))
` 

in the actual code. Why would the pod install of mine have the wrong line of code in it?

**Comment by yuryrabiankou** [comment]
@d7laungani Looks like the 0.06 version https://github.com/d7laungani/DLLocalNotifications/blob/0.06/DLLocalNotifications/DLLocalNotifications.swift is different from the master version https://github.com/d7laungani/DLLocalNotifications/blob/master/DLLocalNotifications/DLLocalNotifications.swift 

The 0.06 release doesn't compile

**Comment by d7laungani** [comment]
Yes sir, Thanks for that. I have updated the pod to 0.07 to match the current version of the code.
