### ISSUE TITLE
CancelNotification crash

### ISSUE THREAD

**Issue by 29satnam** [d7laungani/DLLocalNotifications#29]
There's a crash when I call method:
`scheduler.cancelNotification(notification:"Identifier")`

**Comment by Tliens** [comment]
me too

**Comment by Tliens** [comment]
fix 


// Cancel the notification if scheduled or queued
    public func cancelNotification (notification: DLNotification) {
        
        UNUserNotificationCenter.current().removePendingNotificationRequests(withIdentifiers: [notification.identifier!])
        let queue = DLQueue.queue.notificationsQueue()
        var i = 0
        for noti in queue {
            if notification.identifier == noti.identifier {
                DLQueue.queue.removeAtIndex(i)
                break
            }
            i += 1
        }
        notification.scheduled = false
    }

**Comment by d7laungani** [comment]
This is now fixed.
