### ISSUE TITLE
unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by n4zg** [d7laungani/DLLocalNotifications#3]
`let scheduler = DLNotificationScheduler()
        let standingCategory = DLCategory(categoryIdentifier: "standingReminder")
        standingCategory.addActionButton(identifier: "willStand", title: "Ok, got it")
        standingCategory.addActionButton(identifier: "willNotStand", title: "Cannot")
        scheduler.scheduleCategories(categories: [standingCategory])
`

getting the following error
fatal error: unexpectedly found nil while unwrapping an Optional value
2017-03-12 14:24:09.727084  fatal error: unexpectedly found nil while unwrapping an Optional value

any suggestions please

**Comment by d7laungani** [comment]
I fixed it. Update your pod and it should work.
