### ISSUE TITLE
Not showing Action Button

### ISSUE THREAD

**Issue by n4zg** [d7laungani/DLLocalNotifications#4]
Im trying to show action buttons with the notification 

`    func dailyNotification(){
        
        let firstNotification = DLNotification(identifier: "firstNotification", alertTitle: "Notificaiton Alert", alertBody: "You have successfully created a notification", date: Date(), repeats: .Minute)
        
        // You can now change the repeat interval here
        firstNotification.repeatInterval = .Minute
        
        // You can add a launch image name
        firstNotification.launchImageName = "logo_ad.jpg"
        
        let scheduler = DLNotificationScheduler()
       
        let standingCategory = DLCategory(categoryIdentifier: "standingReminder")
        
        standingCategory.addActionButton(identifier: "willStand", title: "Ok, got it")
        standingCategory.addActionButton(identifier: "willNotStand", title: "Cannot")
        
        scheduler.scheduleCategories(categories: [standingCategory])
        scheduler.scheduleNotification(notification: firstNotification)
        firstNotification.category = "standingReminder"
    }`

any reason why this isnt working 

thank you

**Comment by d7laungani** [comment]
Try setting the category before scheduling the notification like so: 

   scheduler.scheduleCategories(categories: [standingCategory])
  firstNotification.category = "standingReminder"
    scheduler.scheduleNotification(notification: firstNotification)

**Comment by d7laungani** [comment]
I am going to go ahead and close this. Let me know if you still have a problem.

**Comment by n4zg** [comment]
HI Thanks for the code, now i can get the action button to show, but the
problem i am having now is if i set the notification on daily interval im
not getting the notification the following day.

Any suggestions

Thanks

**Comment by d7laungani** [comment]
I'll look into it.

**Comment by d7laungani** [comment]
I tested it and it seems to be working fine. Check the next trigger date.
