### ISSUE TITLE
Hourly schedule doesn't working

### ISSUE THREAD

**Issue by ezar** [d7laungani/DLLocalNotifications#5]
I use .hourly schedule and when I getPendingNotificationRequests, says dd-mm-yyyy 00:00:00.
Seems that It's scheduled for midnight.
Why?

**Comment by ezar** [comment]
Anyone?

**Comment by d7laungani** [comment]
Update the pod to version 0.06 and it should work fine.

**Comment by d7laungani** [comment]
is it working now @ezar ?

**Comment by ezar** [comment]
No :(

**Comment by d7laungani** [comment]
Can you post the exact code you are trying to run.
