### ISSUE TITLE
Schedule at same time every day

### ISSUE THREAD

**Issue by ezar** [d7laungani/DLLocalNotifications#7]
Hi,
It's a fantastic library, but I want to schedule a notificacion every day at same hour. Is it possible?
Regards,

**Comment by ezar** [comment]
Anyone?

**Comment by d7laungani** [comment]
You can just change the repeats property when setting up a notification.

let firstNotification = DLNotification(identifier: "firstNotification", alertTitle: "Notificaiton Alert", alertBody: "You have successfully created a notification", date: Date(), repeats: .Daily)

let scheduler = DLNotificationScheduler()
scheduler.scheduleNotification(notification: firstNotification)

**Comment by ezar** [comment]
But... Can I specify a fixed hour to repeat?
Regards,

**Comment by d7laungani** [comment]
It will get the hour or the time you set in the date parameter. If you want it to repeat at 9am and 9pm everyday then you will make two notifications: one at 9am and another at 9pm on the current day. Then you can set the repeats option to .Daily for it to repeat everyday at the exact same time.

**Comment by d7laungani** [comment]
fix #5 This should make what you want to do work.
