### ISSUE TITLE
Support ios 8+

### ISSUE THREAD

**Issue by piv199** [d7laungani/DLLocalNotifications#8]
Could be added support for handling ios9 and ios10 in different way with the same API?

**Comment by d7laungani** [comment]
Unfortunately the User Notifications framework is supported from IOS 10+ and a new os is just around the corner so I did not feel it worth while to re implement the library using local notifications, which is deprecated. However, I can point you to another library that is compatible with IOS 9. https://github.com/ahmedabadie/ABNScheduler
